// src/components/mastHeader/Navigation.vue
<template>
  <nav>
    <ul>
      <li>
        <button @click="toggleExpanded">works()</button>
        <ul v-show="defaultExpanded.works">
          <li>
            <router-link :to="'/works/art'" @click="collapseAll">.art();</router-link>
          </li>
          <li>
            <router-link :to="'/works/professional'" @click="collapseAll">.professional();</router-link>
          </li>
        </ul>
      </li>
      <li>
        <router-link to="/about">about();</router-link>
      </li>
      <li>
        <button @click="toggleExpanded">contact()</button>
        <ul v-show="defaultExpanded.contact">
          <li>
            <a href="https://www.linkedin.com/in/johnnyrayalt/" target="_blank" rel="noreferrer">.linkedIn();</a>
          </li>
          <li>
            <a href="mailto:johnnyrayalt@gmail.com" target="_blank" rel="noreferrer">.email();</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="https://github.com/johnnyrayalt" target="_blank" rel="noreferrer">github</a>
      </li>
    </ul>
  </nav>
</template>

<script lang="ts">
import { Vue } from 'vue-class-component';
import { Watch } from 'vue-property-decorator';

export default class Navigation extends Vue {
  defaultExpanded: { [name: string]: boolean } = {
    works: false,
    contact: false,
    main: false,
  };

  @Watch('defaultExpanded')
  toggleExpanded(e: any): void {
    const expand = e.target.innerText;

    Object.keys(this.defaultExpanded).forEach((key) => {
      expand.includes(key)
        ? (this.defaultExpanded[key] = !this.defaultExpanded[key])
        : (this.defaultExpanded[key] = false);
    });
  }

  @Watch('defaultExpanded')
  collapseAll(): void {
    Object.keys(this.defaultExpanded).forEach((key) => (this.defaultExpanded[key] = false));
  }
}
</script>

// components/common/navigation/Navigation.tsx
import React, { FC, useState } from 'react';
import Link from 'next/link';
import { BooleanObj } from '../../../types/BooleanObj';
import { EXPANDED_STATE_KEYS, IMAGE_ROOTS } from '../../../assets/constants';

const Navigation: FC = (): JSX.Element => {
	const defaultExpanded: BooleanObj = {
		works: false,
		socials: false,
		main: false,
	}

	const [expanded, setExpanded] = useState<BooleanObj>(defaultExpanded);

	const handleChangeExpanded = (stateToChange: string): void =>
		setExpanded({
			[stateToChange.toLocaleLowerCase()]: !expanded[stateToChange.toLocaleLowerCase()]
		})

	const resetExpandedOnClick = (): void =>
		setExpanded(defaultExpanded);

	return (
		<div id='navigation-container'>
			<div className='navigation-links-container'>
				<nav>
					<ul className='nav-ul'>
						<li className='nav-li'>
							<button onClick={() => handleChangeExpanded(EXPANDED_STATE_KEYS.WORKS)} className='link btn'>
								works(↳)
							</button>
							{expanded.works && (
								<ul className='sub-nav-ul'>
									<li className='sub-nav-li'>
										<Link href={`/projects/${IMAGE_ROOTS.art}`} passHref>
											<div className='sub-nav-link link' onClick={() => resetExpandedOnClick()}>
												.art(→);
											</div>
										</Link>
									</li>
									<li className='sub-nav-li'>
										<Link href={`/projects/${IMAGE_ROOTS.professional}`} passHref>
											<div className='sub-nav-link link' onClick={() => resetExpandedOnClick()}>
												.professional(→);
											</div>
										</Link>
									</li>
								</ul>
							)}
						</li>
						<li className='nav-li'>
							<Link href={`/about`} passHref>
								<div>about(→);</div>
							</Link>
						</li>
						<li className='nav-li'>
							<button onClick={() => handleChangeExpanded(EXPANDED_STATE_KEYS.SOCIALS)} className='link btn'>
								contacts(↳)
							</button>
							{expanded.socials && (
								<ul className='sub-nav-ul'>
									<li className='sub-nav-li'>
										<a
											className='link'
											href='https://linkedin.com/in/johnnyrayalt'
											rel='noopener noreferrer'
											target='_blank'
											onClick={() => resetExpandedOnClick()}
										>
											.linkedin(&#x02197;);
										</a>
									</li>
									<li className='sub-nav-li'>
										<a
											className='link'
											href='mailto:johnnyrayalt@gmail.com'
											onClick={() => resetExpandedOnClick()}
										>
											.email(&#x02197;);
										</a>
									</li>
								</ul>
							)}
						</li>
						<li className='nav-li'>
							<a className='link' href='https://github.com/johnnyrayalt' rel='noopener noreferrer' target='_blank'>
								github(&#x02197;);
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	);
}

export default Navigation;
